//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string IdTeam { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
